//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class constantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal constantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.constantes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;159&apos;,&apos;676&apos;).
        /// </summary>
        internal static string OBJCentros {
            get {
                return ResourceManager.GetString("OBJCentros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;013&apos;,&apos;338&apos;,&apos;726&apos;,&apos;831&apos;,&apos;825&apos;,&apos;B28&apos;).
        /// </summary>
        internal static string OBJClientes {
            get {
                return ResourceManager.GetString("OBJClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;063&apos;,&apos;A39&apos;).
        /// </summary>
        internal static string OBJContacto {
            get {
                return ResourceManager.GetString("OBJContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;625&apos;,&apos;A26&apos;).
        /// </summary>
        internal static string OBJEfectosCli {
            get {
                return ResourceManager.GetString("OBJEfectosCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;626&apos;,&apos;A28&apos;).
        /// </summary>
        internal static string OBJEfectosPro {
            get {
                return ResourceManager.GetString("OBJEfectosPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 017.
        /// </summary>
        internal static string OBJFacturasCli {
            get {
                return ResourceManager.GetString("OBJFacturasCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;468&apos;,&apos;A40&apos;).
        /// </summary>
        internal static string OBJLContactos {
            get {
                return ResourceManager.GetString("OBJLContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;038&apos;,&apos;A02&apos;).
        /// </summary>
        internal static string OBJPersonal {
            get {
                return ResourceManager.GetString("OBJPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;009&apos;,&apos;B27&apos;).
        /// </summary>
        internal static string OBJProveedores {
            get {
                return ResourceManager.GetString("OBJProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;04&apos;,&apos;59&apos;).
        /// </summary>
        internal static string OBJSeguimientoComercial {
            get {
                return ResourceManager.GetString("OBJSeguimientoComercial", resourceCulture);
            }
        }
    }
}
