//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string AltoVentana {
            get {
                return ResourceManager.GetString("AltoVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string AltoVentana2 {
            get {
                return ResourceManager.GetString("AltoVentana2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 750.
        /// </summary>
        internal static string AnchoVentana {
            get {
                return ResourceManager.GetString("AnchoVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 950.
        /// </summary>
        internal static string AnchoVentana2 {
            get {
                return ResourceManager.GetString("AnchoVentana2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lib/estilos/.
        /// </summary>
        internal static string App_themes {
            get {
                return ResourceManager.GetString("App_themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF7310.
        /// </summary>
        internal static string color_titulo_pagina {
            get {
                return ResourceManager.GetString("color_titulo_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D0C9C1.
        /// </summary>
        internal static string color_titulo_tabla {
            get {
                return ResourceManager.GetString("color_titulo_tabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir nuevo registro.
        /// </summary>
        internal static string LitAnyadir {
            get {
                return ResourceManager.GetString("LitAnyadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string LitBorrar {
            get {
                return ResourceManager.GetString("LitBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string LitCancelar {
            get {
                return ResourceManager.GetString("LitCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGANDO APLICACIÓN. ESPERE POR FAVOR.......
        /// </summary>
        internal static string LitCargandoApi {
            get {
                return ResourceManager.GetString("LitCargandoApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de borrar el registro actual? No se podrá recuperar..
        /// </summary>
        internal static string LitConfirmBorrar {
            get {
                return ResourceManager.GetString("LitConfirmBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene.
        /// </summary>
        internal static string LitContiene {
            get {
                return ResourceManager.GetString("LitContiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string LitEditar {
            get {
                return ResourceManager.GetString("LitEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar datos.
        /// </summary>
        internal static string LitGuardar {
            get {
                return ResourceManager.GetString("LitGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual a.
        /// </summary>
        internal static string LitIgual {
            get {
                return ResourceManager.GetString("LitIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string LitLeftPosBT {
            get {
                return ResourceManager.GetString("LitLeftPosBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso legal.
        /// </summary>
        internal static string LitMsgAvisoLegal {
            get {
                return ResourceManager.GetString("LitMsgAvisoLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido actualizar el motivo seleccionado..
        /// </summary>
        internal static string LitMsgErrorActualizarMotivo {
            get {
                return ResourceManager.GetString("LitMsgErrorActualizarMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido eliminar el motivo seleccionado..
        /// </summary>
        internal static string LitMsgErrorElimnarMotivo {
            get {
                return ResourceManager.GetString("LitMsgErrorElimnarMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El motivo indicado ya existe.
        /// </summary>
        internal static string LitMsgErrorExisteMotivo {
            get {
                return ResourceManager.GetString("LitMsgErrorExisteMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido insertar el motivo seleccionado..
        /// </summary>
        internal static string LitMsgErrorInsertarMotivo {
            get {
                return ResourceManager.GetString("LitMsgErrorInsertarMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información general.
        /// </summary>
        internal static string LitMsgInformacionGeneral {
            get {
                return ResourceManager.GetString("LitMsgInformacionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay resultados para la búsqueda solicitada.
        /// </summary>
        internal static string LitMsgNoResultadosBusqueda {
            get {
                return ResourceManager.GetString("LitMsgNoResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolución mínima de 800x600 © Telefónica S.A.U - Todos los derechos reservados.
        /// </summary>
        internal static string LitMsgResolucion {
            get {
                return ResourceManager.GetString("LitMsgResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-GESTION FACTURA CETEL:Sistema de Gestión Comercial E*GESTICET.
        /// </summary>
        internal static string LitPieListados {
            get {
                return ResourceManager.GetString("LitPieListados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string LitTeclaCancelar {
            get {
                return ResourceManager.GetString("LitTeclaCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 113.
        /// </summary>
        internal static string LitTeclaGuardar {
            get {
                return ResourceManager.GetString("LitTeclaGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termina en.
        /// </summary>
        internal static string LitTermina {
            get {
                return ResourceManager.GetString("LitTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos Personalizables.
        /// </summary>
        internal static string LitTitCamposPerso {
            get {
                return ResourceManager.GetString("LitTitCamposPerso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string LitTodos {
            get {
                return ResourceManager.GetString("LitTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string LitTopPosBT {
            get {
                return ResourceManager.GetString("LitTopPosBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha desde no puede estar vacío..
        /// </summary>
        internal static string LitVacioFechaDesde {
            get {
                return ResourceManager.GetString("LitVacioFechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo fecha hasta no puede estar vacío..
        /// </summary>
        internal static string LitVacioFechaHasta {
            get {
                return ResourceManager.GetString("LitVacioFechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cliente.
        /// </summary>
        internal static string LitVerCliente {
            get {
                return ResourceManager.GetString("LitVerCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Proyecto.
        /// </summary>
        internal static string LitVerProyecto {
            get {
                return ResourceManager.GetString("LitVerProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string MostrarPie {
            get {
                return ResourceManager.GetString("MostrarPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;070&apos;).
        /// </summary>
        internal static string OBJProyectos {
            get {
                return ResourceManager.GetString("OBJProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&apos;013&apos;, &apos;338&apos;).
        /// </summary>
        internal static string ONJClientes {
            get {
                return ResourceManager.GetString("ONJClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 118.
        /// </summary>
        internal static string TeclaBuscar {
            get {
                return ResourceManager.GetString("TeclaBuscar", resourceCulture);
            }
        }
    }
}
