//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ico2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ico2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ico2", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_search.png.
        /// </summary>
        internal static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string btn_search_h {
            get {
                return ResourceManager.GetString("btn_search_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string btn_search_w {
            get {
                return ResourceManager.GetString("btn_search_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/Calendar_scheduleHS.png.
        /// </summary>
        internal static string CalendarFolder {
            get {
                return ResourceManager.GetString("CalendarFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Calendar_h {
            get {
                return ResourceManager.GetString("Calendar_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Calendar_w {
            get {
                return ResourceManager.GetString("Calendar_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/CarpetaAbierta.gif.
        /// </summary>
        internal static string CarpetaAbierta {
            get {
                return ResourceManager.GetString("CarpetaAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string CarpetaAbierta_h {
            get {
                return ResourceManager.GetString("CarpetaAbierta_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string CarpetaAbierta_w {
            get {
                return ResourceManager.GetString("CarpetaAbierta_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/CarpetaCerrada.gif.
        /// </summary>
        internal static string CarpetaCerrada {
            get {
                return ResourceManager.GetString("CarpetaCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string CarpetaCerrada_h {
            get {
                return ResourceManager.GetString("CarpetaCerrada_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string CarpetaCerrada_w {
            get {
                return ResourceManager.GetString("CarpetaCerrada_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/checkbox_24x24_fe.png.
        /// </summary>
        internal static string cbChecked {
            get {
                return ResourceManager.GetString("cbChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/checkbox_unchecked_24x24_fe.png.
        /// </summary>
        internal static string cbUnchecked {
            get {
                return ResourceManager.GetString("cbUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_openfolder.png.
        /// </summary>
        internal static string CloseFolder {
            get {
                return ResourceManager.GetString("CloseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_collapse_footer.png.
        /// </summary>
        internal static string CloseFooter {
            get {
                return ResourceManager.GetString("CloseFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_collapse_all.png.
        /// </summary>
        internal static string CollapseSections {
            get {
                return ResourceManager.GetString("CollapseSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/log_form_imp.jpg.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Document_h {
            get {
                return ResourceManager.GetString("Document_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Document_w {
            get {
                return ResourceManager.GetString("Document_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/GenerarInforme.gif.
        /// </summary>
        internal static string GenerarInforme {
            get {
                return ResourceManager.GetString("GenerarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenerarInforme_h {
            get {
                return ResourceManager.GetString("GenerarInforme_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenerarInforme_w {
            get {
                return ResourceManager.GetString("GenerarInforme_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_home.png.
        /// </summary>
        internal static string icHome {
            get {
                return ResourceManager.GetString("icHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/anotar_caja.png.
        /// </summary>
        internal static string imgActualizarCentro {
            get {
                return ResourceManager.GetString("imgActualizarCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/amortization.png.
        /// </summary>
        internal static string imgAmortization {
            get {
                return ResourceManager.GetString("imgAmortization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string imgAmortization_h {
            get {
                return ResourceManager.GetString("imgAmortization_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string imgAmortization_w {
            get {
                return ResourceManager.GetString("imgAmortization_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_banner.jpg.
        /// </summary>
        internal static string imgBannerHome {
            get {
                return ResourceManager.GetString("imgBannerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/facturas_emitidas.png.
        /// </summary>
        internal static string imgBorrarCentro {
            get {
                return ResourceManager.GetString("imgBorrarCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_servicios.gif.
        /// </summary>
        internal static string imgBtnServicios {
            get {
                return ResourceManager.GetString("imgBtnServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/borra_fila.png.
        /// </summary>
        internal static string imgCancelGridview {
            get {
                return ResourceManager.GetString("imgCancelGridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/datos_laborales.png.
        /// </summary>
        internal static string imgCandidatos {
            get {
                return ResourceManager.GetString("imgCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/cost_sharing.png.
        /// </summary>
        internal static string imgCostDoc {
            get {
                return ResourceManager.GetString("imgCostDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string imgCostDoc_h {
            get {
                return ResourceManager.GetString("imgCostDoc_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string imgCostDoc_w {
            get {
                return ResourceManager.GetString("imgCostDoc_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/borra_fila.png.
        /// </summary>
        internal static string imgDeleteGridview {
            get {
                return ResourceManager.GetString("imgDeleteGridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/document_icon.png.
        /// </summary>
        internal static string imgDocDocument {
            get {
                return ResourceManager.GetString("imgDocDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgDocDocument_h {
            get {
                return ResourceManager.GetString("imgDocDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgDocDocument_w {
            get {
                return ResourceManager.GetString("imgDocDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/editar.png.
        /// </summary>
        internal static string imgEditGridview {
            get {
                return ResourceManager.GetString("imgEditGridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/editRCDMKP.png.
        /// </summary>
        internal static string imgEditGridviewMKPRCD {
            get {
                return ResourceManager.GetString("imgEditGridviewMKPRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/excel_icon.png.
        /// </summary>
        internal static string imgExcelDocument {
            get {
                return ResourceManager.GetString("imgExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgExcelDocument_h {
            get {
                return ResourceManager.GetString("imgExcelDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgExcelDocument_w {
            get {
                return ResourceManager.GetString("imgExcelDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/add_item.png.
        /// </summary>
        internal static string imgGridViewDuplicate {
            get {
                return ResourceManager.GetString("imgGridViewDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_ico_search.png.
        /// </summary>
        internal static string imgGridViewSearch {
            get {
                return ResourceManager.GetString("imgGridViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string imgGridview_h {
            get {
                return ResourceManager.GetString("imgGridview_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string imgGridview_w {
            get {
                return ResourceManager.GetString("imgGridview_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_ayuda.gif.
        /// </summary>
        internal static string imgHelp {
            get {
                return ResourceManager.GetString("imgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/historial.png.
        /// </summary>
        internal static string imgHistorial {
            get {
                return ResourceManager.GetString("imgHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/imagen_icono.png.
        /// </summary>
        internal static string imgImageDocument {
            get {
                return ResourceManager.GetString("imgImageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgImageDocument_h {
            get {
                return ResourceManager.GetString("imgImageDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgImageDocument_w {
            get {
                return ResourceManager.GetString("imgImageDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/logo_movistar.png.
        /// </summary>
        internal static string imgLogoMovistar {
            get {
                return ResourceManager.GetString("imgLogoMovistar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/logo_telefonica.png.
        /// </summary>
        internal static string imgLogoTefonica {
            get {
                return ResourceManager.GetString("imgLogoTefonica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/open_info.png.
        /// </summary>
        internal static string ImgOpenInfoLF {
            get {
                return ResourceManager.GetString("ImgOpenInfoLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ImgOpenInfoLF_h {
            get {
                return ResourceManager.GetString("ImgOpenInfoLF_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ImgOpenInfoLF_w {
            get {
                return ResourceManager.GetString("ImgOpenInfoLF_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pdf_icon.png.
        /// </summary>
        internal static string imgPdfDocument {
            get {
                return ResourceManager.GetString("imgPdfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgPdfDocument_h {
            get {
                return ResourceManager.GetString("imgPdfDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgPdfDocument_w {
            get {
                return ResourceManager.GetString("imgPdfDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/info.png.
        /// </summary>
        internal static string ImgPlusInfo {
            get {
                return ResourceManager.GetString("ImgPlusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ImgPlusInfo_h {
            get {
                return ResourceManager.GetString("ImgPlusInfo_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ImgPlusInfo_w {
            get {
                return ResourceManager.GetString("ImgPlusInfo_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/powepoint_icono.png.
        /// </summary>
        internal static string imgPowepointDocument {
            get {
                return ResourceManager.GetString("imgPowepointDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgPowepointDocument_h {
            get {
                return ResourceManager.GetString("imgPowepointDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgPowepointDocument_w {
            get {
                return ResourceManager.GetString("imgPowepointDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/facturas_emitidas.png.
        /// </summary>
        internal static string imgPublicarCentro {
            get {
                return ResourceManager.GetString("imgPublicarCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_cloud.png.
        /// </summary>
        internal static string imgServicesCloud {
            get {
                return ResourceManager.GetString("imgServicesCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_digital.png.
        /// </summary>
        internal static string imgServicesDigitales {
            get {
                return ResourceManager.GetString("imgServicesDigitales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_m2m.png.
        /// </summary>
        internal static string imgServicesM2M {
            get {
                return ResourceManager.GetString("imgServicesM2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/ic_security.png.
        /// </summary>
        internal static string imgServicesSecurity {
            get {
                return ResourceManager.GetString("imgServicesSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/tag_aplicateca.png.
        /// </summary>
        internal static string imgTagAplicateca {
            get {
                return ResourceManager.GetString("imgTagAplicateca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/aceptar_guardar.png.
        /// </summary>
        internal static string imgUpdateGridview {
            get {
                return ResourceManager.GetString("imgUpdateGridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/word_icon.png.
        /// </summary>
        internal static string imgWordDocument {
            get {
                return ResourceManager.GetString("imgWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgWordDocument_h {
            get {
                return ResourceManager.GetString("imgWordDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgWordDocument_w {
            get {
                return ResourceManager.GetString("imgWordDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/zip_icon.png.
        /// </summary>
        internal static string imgZipDocument {
            get {
                return ResourceManager.GetString("imgZipDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgZipDocument_h {
            get {
                return ResourceManager.GetString("imgZipDocument_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string imgZipDocument_w {
            get {
                return ResourceManager.GetString("imgZipDocument_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ImportaData_w {
            get {
                return ResourceManager.GetString("ImportaData_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/impot_data.png.
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ImportData_h {
            get {
                return ResourceManager.GetString("ImportData_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/line_vertical_blue.png.
        /// </summary>
        internal static string LineVerticalBlue {
            get {
                return ResourceManager.GetString("LineVerticalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_nocollapse_all.png.
        /// </summary>
        internal static string NoCollapseSections {
            get {
                return ResourceManager.GetString("NoCollapseSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_closefolder.png.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_expand_footer.png.
        /// </summary>
        internal static string OpenFooter {
            get {
                return ResourceManager.GetString("OpenFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/icono_outlook.gif.
        /// </summary>
        internal static string outlook {
            get {
                return ResourceManager.GetString("outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/RadioButton_checked.png.
        /// </summary>
        internal static string RadioButton_checked {
            get {
                return ResourceManager.GetString("RadioButton_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/RadioButton_unchecked.png.
        /// </summary>
        internal static string RadioButton_unchecked {
            get {
                return ResourceManager.GetString("RadioButton_unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/icono_home.png.
        /// </summary>
        internal static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ReturnHome_h {
            get {
                return ResourceManager.GetString("ReturnHome_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ReturnHome_w {
            get {
                return ResourceManager.GetString("ReturnHome_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/numero_serie.png.
        /// </summary>
        internal static string serialNumber {
            get {
                return ResourceManager.GetString("serialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string serialNumber_h {
            get {
                return ResourceManager.GetString("serialNumber_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string serialNumber_w {
            get {
                return ResourceManager.GetString("serialNumber_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/synchronize_process.png.
        /// </summary>
        internal static string SynchronizeProcess {
            get {
                return ResourceManager.GetString("SynchronizeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SynchronizeProcess_h {
            get {
                return ResourceManager.GetString("SynchronizeProcess_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SynchronizeProcess_w {
            get {
                return ResourceManager.GetString("SynchronizeProcess_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/folder_close.gif.
        /// </summary>
        internal static string TreeCollapsedFolder {
            get {
                return ResourceManager.GetString("TreeCollapsedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeCollapsedFolder_h {
            get {
                return ResourceManager.GetString("TreeCollapsedFolder_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeCollapsedFolder_w {
            get {
                return ResourceManager.GetString("TreeCollapsedFolder_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/folder_open.gif.
        /// </summary>
        internal static string TreeExpandedFolder {
            get {
                return ResourceManager.GetString("TreeExpandedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeExpandedFolder_h {
            get {
                return ResourceManager.GetString("TreeExpandedFolder_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeExpandedFolder_w {
            get {
                return ResourceManager.GetString("TreeExpandedFolder_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/folder_empty.gif.
        /// </summary>
        internal static string TreeNoExpandedFolder {
            get {
                return ResourceManager.GetString("TreeNoExpandedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeNoExpandedFolder_h {
            get {
                return ResourceManager.GetString("TreeNoExpandedFolder_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TreeNoExpandedFolder_w {
            get {
                return ResourceManager.GetString("TreeNoExpandedFolder_w", resourceCulture);
            }
        }
    }
}
