//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class init {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal init() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.init", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAAS EVERILION.
        /// </summary>
        internal static string defaultTitle {
            get {
                return ResourceManager.GetString("defaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/background_head.png.
        /// </summary>
        internal static string imgBackgroundHead {
            get {
                return ResourceManager.GetString("imgBackgroundHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_collapse_footer.png.
        /// </summary>
        internal static string imgHideFooter {
            get {
                return ResourceManager.GetString("imgHideFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_collapse_menu.png.
        /// </summary>
        internal static string imgHideMenu {
            get {
                return ResourceManager.GetString("imgHideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/icono_home.png.
        /// </summary>
        internal static string imgHome {
            get {
                return ResourceManager.GetString("imgHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_expand_footer.png.
        /// </summary>
        internal static string imgShowFooter {
            get {
                return ResourceManager.GetString("imgShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/btn_expand_menu.png.
        /// </summary>
        internal static string imgShowMenu {
            get {
                return ResourceManager.GetString("imgShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/caballin.ico.
        /// </summary>
        internal static string imgTitle {
            get {
                return ResourceManager.GetString("imgTitle", resourceCulture);
            }
        }
    }
}
