//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modulos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Modulos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B0.
        /// </summary>
        internal static string ModCitas {
            get {
                return ResourceManager.GetString("ModCitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27,46,68.
        /// </summary>
        internal static string ModCMS {
            get {
                return ResourceManager.GetString("ModCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04,59,65,C4.
        /// </summary>
        internal static string ModComercial {
            get {
                return ResourceManager.GetString("ModComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1,72.
        /// </summary>
        internal static string ModComsumosPropios {
            get {
                return ResourceManager.GetString("ModComsumosPropios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13,47,58,63,56,A5.
        /// </summary>
        internal static string ModContabilidad {
            get {
                return ResourceManager.GetString("ModContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F0.
        /// </summary>
        internal static string ModDOMS {
            get {
                return ResourceManager.GetString("ModDOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07,28,B1,B5.
        /// </summary>
        internal static string ModEComerce {
            get {
                return ResourceManager.GetString("ModEComerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28,67.
        /// </summary>
        internal static string ModEshop {
            get {
                return ResourceManager.GetString("ModEshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06,C9,F5.
        /// </summary>
        internal static string ModFidelizacion {
            get {
                return ResourceManager.GetString("ModFidelizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88.
        /// </summary>
        internal static string ModFidelizacionPremium {
            get {
                return ResourceManager.GetString("ModFidelizacionPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3.
        /// </summary>
        internal static string ModFreeGrant {
            get {
                return ResourceManager.GetString("ModFreeGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E4.
        /// </summary>
        internal static string ModFreemiumGrant {
            get {
                return ResourceManager.GetString("ModFreemiumGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string ModLogisticaAlmacenes {
            get {
                return ResourceManager.GetString("ModLogisticaAlmacenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50,71,72,73,74.
        /// </summary>
        internal static string ModOrCU {
            get {
                return ResourceManager.GetString("ModOrCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03,64,82,83,C8.
        /// </summary>
        internal static string ModPostVenta {
            get {
                return ResourceManager.GetString("ModPostVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E5.
        /// </summary>
        internal static string ModPremiumGrant {
            get {
                return ResourceManager.GetString("ModPremiumGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09,69.
        /// </summary>
        internal static string ModProduccion {
            get {
                return ResourceManager.GetString("ModProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05,C2,C3.
        /// </summary>
        internal static string ModProyectos {
            get {
                return ResourceManager.GetString("ModProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        internal static string ModuloBasico {
            get {
                return ResourceManager.GetString("ModuloBasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58,56,63,62.
        /// </summary>
        internal static string ModuloCCostes {
            get {
                return ResourceManager.GetString("ModuloCCostes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E9.
        /// </summary>
        internal static string ModVenta2PasosXenteo {
            get {
                return ResourceManager.GetString("ModVenta2PasosXenteo", resourceCulture);
            }
        }
    }
}
