//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Styles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Styles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Styles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyGrid.css.
        /// </summary>
        internal static string compGrid {
            get {
                return ResourceManager.GetString("compGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI/jquery.ui.all.css;UI/jquery.ui.tabs.net.css.
        /// </summary>
        internal static string compTabs {
            get {
                return ResourceManager.GetString("compTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;.
        /// </summary>
        internal static string type00 {
            get {
                return ResourceManager.GetString("type00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string type00s {
            get {
                return ResourceManager.GetString("type00s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;generalData.css;Sections.css;ExtraLink.css;Calendar.css;.
        /// </summary>
        internal static string type01 {
            get {
                return ResourceManager.GetString("type01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StySections.css;StyObject.css.
        /// </summary>
        internal static string type01s {
            get {
                return ResourceManager.GetString("type01s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;.
        /// </summary>
        internal static string type02 {
            get {
                return ResourceManager.GetString("type02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;generalData.css;Sections.css;ExtraLink.css;Calendar.css;UI/jquery.ui.all.css.
        /// </summary>
        internal static string type03 {
            get {
                return ResourceManager.GetString("type03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;.
        /// </summary>
        internal static string type04 {
            get {
                return ResourceManager.GetString("type04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;Sections.css;Calendar.css;.
        /// </summary>
        internal static string type05 {
            get {
                return ResourceManager.GetString("type05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;.
        /// </summary>
        internal static string type06 {
            get {
                return ResourceManager.GetString("type06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;breadcrumb.css;generalData.css;ExtraLink.css;Calendar.css;elements.css;themes.css.
        /// </summary>
        internal static string type07 {
            get {
                return ResourceManager.GetString("type07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css.
        /// </summary>
        internal static string type08 {
            get {
                return ResourceManager.GetString("type08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css.
        /// </summary>
        internal static string type09 {
            get {
                return ResourceManager.GetString("type09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css.
        /// </summary>
        internal static string type10 {
            get {
                return ResourceManager.GetString("type10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListSearch.css.
        /// </summary>
        internal static string type50 {
            get {
                return ResourceManager.GetString("type50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StySearch.css.
        /// </summary>
        internal static string type50s {
            get {
                return ResourceManager.GetString("type50s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;modal/modal.css.
        /// </summary>
        internal static string type60 {
            get {
                return ResourceManager.GetString("type60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilionp.css;Asistente.css;Botonera.css;modalAsistente.css;ListSearch.css.
        /// </summary>
        internal static string type70 {
            get {
                return ResourceManager.GetString("type70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.css;FootButton.css.
        /// </summary>
        internal static string typeM {
            get {
                return ResourceManager.GetString("typeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyBreadcrumb.css;StyMaster.css.
        /// </summary>
        internal static string typeMs {
            get {
                return ResourceManager.GetString("typeMs", resourceCulture);
            }
        }
    }
}
